# Mark objects as 'ancient' so they are taken out of the OCaml heap.
# $Id: Makefile.config,v 1.2 2006-09-27 14:05:07 rich Exp $

PACKAGE := ancient
VERSION := 0.0.2

ifeq ($(shell hostname),oirase)
TEST_WEBLOGS	:= 1
endif