# Mark objects as 'ancient' so they are taken out of the OCaml heap.
# $Id: Makefile.config,v 1.3 2006-09-27 18:39:44 rich Exp $

PACKAGE := ancient
VERSION := 0.0.3

ifeq ($(shell hostname),oirase)
TEST_WEBLOGS	:= 1
endif