# Mark objects as 'ancient' so they are taken out of the OCaml heap.
# $Id: Makefile.config,v 1.5 2006-09-28 12:40:48 rich Exp $

PACKAGE := ancient
VERSION := 0.0.5

ifeq ($(shell hostname),oirase)
TEST_WEBLOGS	:= 1
endif
